# Generated by Django 2.1.1 on 2018-09-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostForms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('name', models.CharField(max_length=140)),
                ('ls', models.TextField()),
                ('question', models.TextField()),
                ('presentation', models.TextField()),
                ('background', models.TextField()),
                ('perfTask', models.TextField()),
                ('quiz', models.TextField()),
                ('vocab', models.TextField()),
                ('wiki', models.TextField()),
            ],
        ),
    ]
